apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 2
  selector:
    app: myapp
    version: 2.7.1
  template:
    metadata:
      labels:
        app: myapp
        version: 2.7.1
    spec:
      containers:
      - name: my-java-container
        image: maha4iac/myonlinebooking:1
        ports:
        - containerPort: 8080