apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: myapp
    version: 2.7.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myapp
    version: 2.7.2

